[package]
name = "rumpus"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
nalgebra = "0.33.2"
rayon = "1.10.0"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
clap = { version="4.5", features=["derive"] }
