[package]
name = "rumpus"
version = "0.7.0"
license = "GPL-3.0-or-later"
description = "A framework for navigation using skylight polarization."
homepage = "https://benpot.com"
repository = "https://github.com/benjaminpotter/rumpus"
readme = "README.md"
keywords = ["polarization", "raytrace", "navigation", "image"]
edition = "2024"
exclude = ["tests/snapshots/*"]

[dependencies]
rayon = "1.10"
spa = "0.5"
sguaba = "0.9"
uom = "0.37"
thiserror = "2.0"
chrono = "0.4"

[dev-dependencies]
image = { version="0.25", features=["rayon"] }
quickcheck = "1.0"
quickcheck_macros = "1.1"
rstest = "0.26"
approx = "0.5"
insta = "1.46"
anyhow = "1.0"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "image"
harness = false
